ekyna_news_news_admin_home:
    path: ""
    defaults: { _controller: "ekyna_news.news.controller:homeAction" }
    requirements:
        _method: GET

ekyna_news_news_admin_list:
    path: /list
    defaults: { _controller: "ekyna_news.news.controller:listAction" }
    requirements:
        _method: GET|POST

ekyna_news_news_admin_new:
    path: /new
    defaults: { _controller: "ekyna_news.news.controller:newAction" }
    requirements:
        _method: GET|POST

ekyna_news_news_admin_show:
    path: /{newsId}/show
    defaults: { _controller: "ekyna_news.news.controller:showAction" }
    requirements:
        _method: GET
        newsId: \d+

ekyna_news_news_admin_edit:
    path: /{newsId}/edit
    defaults: { _controller: "ekyna_news.news.controller:editAction" }
    requirements:
        _method: GET|POST
        newsId: \d+

ekyna_news_news_admin_tinymce:
    path: /{newsId}/tinymce
    defaults: { _controller: "ekyna_news.news.controller:tinymceAction", field: content }
    requirements:
        _method: GET
        newsId: \d+

ekyna_news_news_admin_toggle:
    path: /{newsId}/toggle/{field}
    defaults: { _controller: "ekyna_news.news.controller:toggleAction", field: enabled }
    requirements:
        _method: GET
        newsId: \d+
        field: \w+

ekyna_news_news_admin_remove:
    path: /{newsId}/remove
    defaults: { _controller: "ekyna_news.news.controller:removeAction" }
    requirements:
        _method: GET|POST
        newsId: \d+
