# Liip Imagine
liip_imagine:
    filter_sets:
        product_thumb:
            quality: 70
            cache: local_media
            data_loader: local_media
            filters:
                thumbnail: { size: [190, 142], mode: outbound }
            post_processors:
                jpegoptim: {}
        product_modal:
            quality: 70
            cache: local_media
            data_loader: local_media
            filters:
                thumbnail: { size: [800, 600], mode: outbound }
            post_processors:
                jpegoptim: {}
        product_gallery_small:
            quality: 70
            cache: local_media
            data_loader: local_media
            filters:
                thumbnail: { size: [168, 126], mode: outbound }
            post_processors:
                jpegoptim: {}
        product_gallery_big:
            quality: 70
            cache: local_media
            data_loader: local_media
            filters:
                thumbnail: { size: [545, 409], mode: outbound }
            post_processors:
                jpegoptim: {}
