ekyna_media_admin:
    resource: "routing/admin.yml"
    prefix:   /admin/content

ekyna_media_download:
    path: /download/media/{key} # TODO /media/download/{key}
    defaults: { _controller: "EkynaMediaBundle:Media:download" }
    requirements:
        _method: GET
        key: "[a-z0-9-\./]+"
    options: { expose: true }

ekyna_media_player:
    path: /media/player/{key}
    defaults: { _controller: "EkynaMediaBundle:Media:player" }
    requirements:
        _method: GET
        key: "[a-z0-9-\./]+"
    options: { expose: true }

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

_oneup_uploader:
    resource: .
    type: uploader
