ekyna_demo_brand_admin_home:
    path: /
    defaults: { _controller: "ekyna_demo.brand.controller:homeAction" }
    requirements:
        _method: GET

ekyna_demo_brand_admin_list:
    path: /list
    defaults: { _controller: "ekyna_demo.brand.controller:listAction" }
    requirements:
        _method: GET|POST

ekyna_demo_brand_admin_new:
    path: /new
    defaults: { _controller: "ekyna_demo.brand.controller:newAction" }
    requirements:
        _method: GET|POST

ekyna_demo_brand_admin_show:
    path: /{brandId}/show
    defaults: { _controller: "ekyna_demo.brand.controller:showAction" }
    requirements:
        _method: GET
        brandId:  \d+

ekyna_demo_brand_admin_edit:
    path: /{brandId}/edit
    defaults: { _controller: "ekyna_demo.brand.controller:editAction" }
    requirements:
        _method: GET|POST
        brandId:  \d+

ekyna_demo_brand_admin_remove:
    path: /{brandId}/remove
    defaults: { _controller: "ekyna_demo.brand.controller:removeAction" }
    requirements:
        _method: GET|POST
        brandId:  \d+
