ekyna_demo_store_admin_home:
    path: ""
    defaults: { _controller: "ekyna_demo.store.controller:homeAction" }
    requirements:
        _method: GET

ekyna_demo_store_admin_list:
    path: /list
    defaults: { _controller: "ekyna_demo.store.controller:listAction" }
    requirements:
        _method: GET|POST

ekyna_demo_store_admin_new:
    path: /new
    defaults: { _controller: "ekyna_demo.store.controller:newAction" }
    requirements:
        _method: GET|POST

ekyna_demo_store_admin_show:
    path: /{storeId}/show
    defaults: { _controller: "ekyna_demo.store.controller:showAction" }
    requirements:
        _method: GET
        storeId: \d+

ekyna_demo_store_admin_edit:
    path: /{storeId}/edit
    defaults: { _controller: "ekyna_demo.store.controller:editAction" }
    requirements:
        _method: GET|POST
        storeId: \d+

ekyna_demo_store_admin_remove:
    path: /{storeId}/remove
    defaults: { _controller: "ekyna_demo.store.controller:removeAction" }
    requirements:
        _method: GET|POST
        storeId: \d+
