ekyna_mailing_recipientList_admin_home:
    path: /
    defaults: { _controller: "ekyna_mailing.recipientList.controller:homeAction" }
    requirements:
        _method: GET

ekyna_mailing_recipientList_admin_list:
    path: /list
    defaults: { _controller: "ekyna_mailing.recipientList.controller:listAction" }
    requirements:
        _method: GET|POST

ekyna_mailing_recipientList_admin_new:
    path: /new
    defaults: { _controller: "ekyna_mailing.recipientList.controller:newAction" }
    requirements:
        _method: GET|POST

ekyna_mailing_recipientList_admin_show:
    path: /{recipientListId}/show
    defaults: { _controller: "ekyna_mailing.recipientList.controller:showAction" }
    requirements:
        _method: GET|POST
        recipientListId: \d+

ekyna_mailing_recipientList_admin_recipients_unlink:
    path: /{recipientListId}/recipients/{recipientId}/unlink
    defaults: { _controller: "ekyna_mailing.recipientList.controller:unlinkRecipientAction" }
    requirements:
        _method: GET|POST
        recipientListId: \d+
        recipientId: \d+

ekyna_mailing_recipientList_admin_edit:
    path: /{recipientListId}/edit
    defaults: { _controller: "ekyna_mailing.recipientList.controller:editAction" }
    requirements:
        _method: GET|POST
        recipientListId: \d+

ekyna_mailing_recipientList_admin_remove:
    path: /{recipientListId}/remove
    defaults: { _controller: "ekyna_mailing.recipientList.controller:removeAction" }
    requirements:
        _method: GET|POST
        recipientListId: \d+
