ekyna_demo_catalog_index:
    pattern: /
    defaults:
        _controller: EkynaDemoBundle:Catalog:index
    requirements:
        _method: GET
    options:
        _cms:
            name: Catalogue
            menus: [main, footer]
            advanced: true

ekyna_demo_catalog_category:
    pattern: /{categorySlug}
    defaults:
        _controller: EkynaDemoBundle:Catalog:category
    requirements:
        _method: GET
        categorySlug: "[a-z0-9-/]+"
    options:
        _cms:
            parent: ekyna_demo_catalog_index

ekyna_demo_catalog_product:
    pattern: /{categorySlug}/{productSlug}.html
    defaults:
        _controller: EkynaDemoBundle:Catalog:product
    requirements:
        _method: GET|POST
        categorySlug: "[a-z0-9-]+"
        productSlug: "[a-z0-9-]+"
    options:
        _cms:
            parent: ekyna_demo_catalog_index
