imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: ekyna.yml }

parameters:
    session.attribute_bag.class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag
    security.authentication.success_handler.class: Ekyna\Bundle\UserBundle\Authentication\AuthenticationSuccessHandler
    fos_elastica.client.class: Ekyna\Bundle\CoreBundle\Elastica\Client
    kernel.var_dir: %kernel.root_dir%/../var

framework:
    esi:        { enabled: true }
    translator: { fallback: "%locale%" }
    secret:      "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_base_urls: { http: ["http:%assets_base_urls%"], ssl: ["https:%assets_base_urls%"] }
        assets_version: v1.0
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ['127.0.0.1', '10.0.0.0/8']
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        cookie_httponly: false # To false if setting session via XMLHttpRequest
        cookie_lifetime: 86400
        #cookie_domain:   "%router.request_context.host%"
        gc_maxlifetime:  86400
    fragments:       { path: /_fragment }
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        []
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        jpegoptim:
            bin: /usr/bin/jpegoptim
            strip_all: true
        less:
            node: "%node_path%"
            node_paths: [/usr/local/lib/node_modules]
            apply_to: "\.less$"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
    twig:
        functions:
            jpegoptim: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # path:     "%database_path%"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    port:       "%mailer_port%"
    auth_mode:  "%mailer_auth_mode%"
    encryption: "%mailer_encryption%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:     { type: memory }

# KNP Snappy
knp_snappy:
    pdf:
        binary:  "%kernel.root_dir%/../bin/wkhtmltopdf-amd64"
    image:
        enabled: false

#jms_translation:
#    configs:
#        app:
#            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src]
#            output_dir: %kernel.root_dir%/Resources/translations
#            #ignored_domains: [routes]
#            excluded_names: ["*TestCase.php", "*Test.php"]
#            excluded_dirs: [cache, data, logs]
#            #extractors: [jms_i18n_routing]

# JMS I18n Routing
jms_i18n_routing:
    default_locale: %locale%
    locales: %locales%
    strategy: prefix_except_default
    cookie:
        enabled: false
    exclusion_pattern: "^/(admin|api)/" # TODO
    routers:
        - "router.default"
        - "ekyna_cms.router"
        - "ekyna_core.router"
