ekyna_media:
    resource: "@EkynaMediaBundle/Resources/config/routing.yml"

ekyna_demo:
    resource: "@EkynaDemoBundle/Resources/config/routing.yml"

ekyna_advertisement:
    resource: "@EkynaAdvertisementBundle/Resources/config/routing.yml"

#ekyna_contact:
#    resource: "@EkynaContactBundle/Resources/config/routing.yml"

ekyna_news:
    resource: "@EkynaNewsBundle/Resources/config/routing.yml"

ekyna_google:
    resource: "@EkynaGoogleBundle/Resources/config/routing.yml"

ekyna_survey:
    resource: "@EkynaSurveyBundle/Resources/config/routing.yml"

ekyna_agenda:
    resource: "@EkynaAgendaBundle/Resources/config/routing.yml"

ekyna_mailing:
    resource: "@EkynaMailingBundle/Resources/config/routing.yml"

ekyna_blog:
    resource: "@EkynaBlogBundle/Resources/config/routing.yml"

ekyna_sitemap:
    resource: "@EkynaSitemapBundle/Resources/config/routing.yml"

ekyna_characteristics:
    resource: "@EkynaCharacteristicsBundle/Resources/config/routing.yml"

ekyna_shipment:
    resource: "@EkynaShipmentBundle/Resources/config/routing.yml"

ekyna_payment:
    resource: "@EkynaPaymentBundle/Resources/config/routing.yml"

ekyna_subscription:
    resource: "@EkynaSubscriptionBundle/Resources/config/routing.yml"

ekyna_cart:
    resource: "@EkynaCartBundle/Resources/config/routing.yml"

ekyna_order:
    resource: "@EkynaOrderBundle/Resources/config/routing.yml"

#ekyna_locality:
#    resource: "@EkynaLocalityBundle/Resources/config/routing.yml"

ekyna_user:
    resource: "@EkynaUserBundle/Resources/config/routing.yml"

ekyna_cms:
    resource: "@EkynaCmsBundle/Resources/config/routing.yml"

ekyna_setting:
    resource: "@EkynaSettingBundle/Resources/config/routing.yml"

ekyna_admin:
    resource: "@EkynaAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

#ekyna_file_manager:
#    resource: "@EkynaFileManagerBundle/Resources/config/routing.yml"
#    prefix:   /filemanager

ekyna_core:
    resource: "@EkynaCoreBundle/Resources/config/routing.yml"
