ekyna_agenda_event_admin_home:
    path: ""
    defaults: { _controller: "ekyna_agenda.event.controller:homeAction" }
    requirements:
        _method: GET

ekyna_agenda_event_admin_list:
    path: /list
    defaults: { _controller: "ekyna_agenda.event.controller:listAction" }
    requirements:
        _method: GET|POST

ekyna_agenda_event_admin_new:
    path: /new
    defaults: { _controller: "ekyna_agenda.event.controller:newAction" }
    requirements:
        _method: GET|POST

ekyna_agenda_event_admin_show:
    path: /{eventId}/show
    defaults: { _controller: "ekyna_agenda.event.controller:showAction" }
    requirements:
        _method: GET
        eventId: \d+
    options:
        expose: true

ekyna_agenda_event_admin_edit:
    path: /{eventId}/edit
    defaults: { _controller: "ekyna_agenda.event.controller:editAction" }
    requirements:
        _method: GET|POST
        eventId: \d+
    options:
        expose: true

ekyna_agenda_event_admin_tinymce:
    path: /{eventId}/tinymce
    defaults: { _controller: "ekyna_agenda.event.controller:tinymceAction", field: content }
    requirements:
        _method: GET
        eventId: \d+

ekyna_agenda_event_admin_toggle:
    path: /{eventId}/toggle/{field}
    defaults: { _controller: "ekyna_agenda.event.controller:toggleAction", field: enabled }
    requirements:
        _method: GET
        eventId: \d+
        field: \w+
    options:
        expose: true

ekyna_agenda_event_admin_remove:
    path: /{eventId}/remove
    defaults: { _controller: "ekyna_agenda.event.controller:removeAction" }
    requirements:
        _method: GET|POST
        eventId: \d+
    options:
        expose: true
