Ekyna\Bundle\MediaBundle\Entity\Media:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: string
            groups: [Default, Manager]
        path:
            expose: true
            groups: [Manager]
            type: string
        size:
            expose: true
            groups: [Manager]
            type: integer
        type:
            expose: true
            groups: [Manager]
            type: string
    virtual_properties:
        guessFilename:
            expose: true
            groups: [Manager]
            serialized_name: filename
            type: string
        getTitle:
            expose: true
            groups: [Default, Manager]
            serialized_name: title
            type: string
        getThumb:
            expose: true
            groups: [Manager]
            serialized_name: thumb
            type: string
        getFront:
            expose: true
            groups: [Default, Manager]
            serialized_name: front
            type: string
