ekyna_blog_category_admin_home:
    path: ""
    defaults: { _controller: "ekyna_blog.category.controller:homeAction" }
    requirements:
        _method: GET

ekyna_blog_category_admin_list:
    path: /list
    defaults: { _controller: "ekyna_blog.category.controller:listAction" }
    requirements:
        _method: GET|POST

ekyna_blog_category_admin_new:
    path: /new
    defaults: { _controller: "ekyna_blog.category.controller:newAction" }
    requirements:
        _method: GET|POST

ekyna_blog_category_admin_show:
    path: /{categoryId}/show
    defaults: { _controller: "ekyna_blog.category.controller:showAction" }
    requirements:
        _method: GET
        categoryId:  \d+

ekyna_blog_category_admin_edit:
    path: /{categoryId}/edit
    defaults: { _controller: "ekyna_blog.category.controller:editAction" }
    requirements:
        _method: GET|POST
        categoryId:  \d+

ekyna_blog_category_admin_move_up:
    path: /{categoryId}/moveup
    defaults: { _controller: "ekyna_blog.category.controller:moveUpAction" }
    requirements:
        _method: GET
        categoryId:  \d+

ekyna_blog_category_admin_move_down:
    path: /{categoryId}/movedown
    defaults: { _controller: "ekyna_blog.category.controller:moveDownAction" }
    requirements:
        _method: GET
        categoryId:  \d+

ekyna_blog_category_admin_toggle:
    path: /{categoryId}/toggle/{field}
    defaults: { _controller: "ekyna_blog.category.controller:toggleAction", field: "enabled" }
    requirements:
        _method: GET
        categoryId:  \d+
        field:  \w+

ekyna_blog_category_admin_remove:
    path: /{categoryId}/remove
    defaults: { _controller: "ekyna_blog.category.controller:removeAction" }
    requirements:
        _method: GET|POST
        categoryId:  \d+
