payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"
    options: { i18n: false }

payum_authorize:
    resource: "@PayumBundle/Resources/config/routing/authorize.xml"
    options: { i18n: false }

payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"
    options: { i18n: false }

ekyna_payment_admin:
    resource: "routing/admin.yml"
    prefix:   /admin/setting

ekyna_payment_notify:
    pattern: /api/payment/notify/{payum_token}
    defaults:
        _controller: EkynaPaymentBundle:Payment:notify
    options: { i18n: false }

ekyna_payment_done:
    pattern: /api/payment/done
    defaults:
        _controller: EkynaPaymentBundle:Payment:done
    options: { i18n: false }
