# Liip Imagine
liip_imagine:
    resolvers:
        local_media:
            web_path:
                cache_prefix: cache/media
    loaders:
        local_media:
            filesystem:
                data_root: %kernel.var_dir%/media
    filter_sets:
        media_thumb:
            quality: 70
            cache: local_media
            data_loader: local_media
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
            post_processors:
                jpegoptim: {}
        media_front:
            quality: 70
            cache: local_media
            data_loader: local_media
            filters:
                thumbnail: { size: [800, 600], mode: inset }
            post_processors:
                jpegoptim: {}
        media_modal:
            quality: 70
            cache: local_media
            data_loader: local_media
            filters:
                thumbnail: { size: [800, 600], mode: inset }
                background: { size: [800, 600], color: '#fff' }
            post_processors:
                jpegoptim: {}
        media_table:
            quality: 70
            cache: local_media
            data_loader: local_media
            filters:
                thumbnail: { size: [24, 24], mode: outbound }
            post_processors:
                jpegoptim: {}
