payum:
    security:
        token_storage:
            Ekyna\Bundle\PaymentBundle\Entity\PayumSecurityToken: { doctrine: orm }
    storages:
        Ekyna\Bundle\PaymentBundle\Entity\TestPayment: { doctrine: orm }
    dynamic_payments:
        sonata_admin: false
        config_storage:
            Ekyna\Bundle\PaymentBundle\Entity\Method: { doctrine: orm }
