ekyna_payment_method_admin_home:
    path: ""
    defaults: { _controller: "ekyna_payment.method.controller:homeAction" }
    requirements:
        _method: GET

ekyna_payment_method_admin_list:
    path: /list
    defaults: { _controller: "ekyna_payment.method.controller:listAction" }
    requirements:
        _method: GET|POST

ekyna_payment_method_admin_new:
    path: /new
    defaults: { _controller: "ekyna_payment.method.controller:newAction" }
    requirements:
        _method: GET|POST

ekyna_payment_method_admin_show:
    path: /{methodId}/show
    defaults: { _controller: "ekyna_payment.method.controller:showAction" }
    requirements:
        _method: GET
        methodId: \d+

ekyna_payment_method_admin_edit:
    path: /{methodId}/edit
    defaults: { _controller: "ekyna_payment.method.controller:editAction" }
    requirements:
        _method: GET|POST
        methodId: \d+

ekyna_payment_method_admin_tinymce:
    path: /{methodId}/tinymce
    defaults: { _controller: "ekyna_payment.method.controller:tinymceAction", field: description }
    requirements:
        _method: GET
        methodId: \d+
        field: "[a-zA-Z0-9]+"

ekyna_payment_method_admin_toggle:
    path: /{methodId}/toggle/{field}
    defaults: { _controller: "ekyna_payment.method.controller:toggleAction", field: enabled }
    requirements:
        _method: GET
        methodId: \d+
        field: \w+

ekyna_payment_method_admin_remove:
    path: /{methodId}/remove
    defaults: { _controller: "ekyna_payment.method.controller:removeAction" }
    requirements:
        _method: GET|POST
        methodId: \d+
