oneup_flysystem:
    adapters:
        local_upload:
            local:
                directory: %kernel.var_dir%/upload
        local_tmp:
            local:
                directory: %kernel.var_dir%/tmp
        local_ftp:
            local:
                directory: %kernel.var_dir%/ftp
        local_tinymce:
            local:
                directory: %kernel.root_dir%/../web/tinymce
    filesystems:
        local_upload:
            adapter: local_upload
            alias:   local_upload_filesystem
            mount:   local_upload
        local_tmp:
            adapter: local_tmp
            alias:   local_tmp_filesystem
            mount:   local_tmp
        local_ftp:
            adapter: local_ftp
            alias: local_ftp_filesystem
            mount: local_ftp
        local_tinymce:
            adapter: local_tinymce
            alias: local_tinymce_filesystem
