stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            tree: true
            sluggable: true
            translatable: false
            timestampable: true
            softdeleteable: true
            sortable: true
            loggable: true