ekyna_mailing_campaign_admin:
    resource: "admin/campaign.yml"
    prefix:   /campaigns

ekyna_mailing_recipientList_admin:
    resource: "admin/recipientList.yml"
    prefix:   /recipient-lists

ekyna_mailing_recipient_admin:
    resource: "admin/recipient.yml"
    prefix:   /recipients
