ekyna_news_example_index:
    path: ""
    defaults: { _controller: EkynaNewsBundle:Example:index }
    requirements:
        _method: GET

ekyna_news_example_detail:
    path: /{slug}
    defaults: { _controller: EkynaNewsBundle:Example:detail }
    requirements:
        _method: GET
        slug: "[a-zA-Z0-9-]+"
