test_test:
    pattern: /test
    defaults:
        _controller: EkynaDemoBundle:Test:test
    requirements:
        _method: GET

test_home:
    pattern: /home
    defaults:
        _controller: EkynaDemoBundle:Test:home
    requirements:
        _method: GET

test_part_one:
    pattern: /part-one
    defaults:
        _controller: EkynaDemoBundle:Test:partOne
    requirements:
        _method: GET

test_part_two:
    pattern: /part-two
    defaults:
        _controller: EkynaDemoBundle:Test:partTwo
    requirements:
        _method: GET

test_part_three:
    pattern: /part-three
    defaults:
        _controller: EkynaDemoBundle:Test:partThree
    requirements:
        _method: GET

test_purge:
    pattern: /test-purge
    defaults:
        _controller: EkynaDemoBundle:Test:purge
    requirements:
        _method: GET
