ekyna_agenda_example_index:
    path: ""
    defaults: { _controller: EkynaAgendaBundle:Example:index }
    requirements:
        _method: GET

ekyna_agenda_example_detail:
    path: /{slug}
    defaults: { _controller: EkynaAgendaBundle:Example:detail }
    requirements:
        _method: GET
        slug: "[a-zA-Z0-9-]+"
